services:
  # Rustってdockerいるのか．．．？コンパイルするだろ？
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rust_schedule
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # 初期化SQLスクリプトをマウント
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
